services:
  image: 'eclipse-mosquitto'
  restart: always
  hostname: 'code.boe-health.com'
  container_name: act-mosquitto
  ports:
    - 1883:1883
    - 9001:9001
  volumes:
    - ./config:/mosquitto/config/
    - ./log:/mosquitto/log/
    - ./data:/mosquitto/data/

